## mindspore.ops.divide(input, other, *, rounding_mode=None) -〉 Tensor
- 输入：
    * input/other必须为int、bool或mindspore的tensor，数据类型为int或bool。
    * rounding_mode为字符串类型，可选值有：None 、 "floor" 和 "trunc"。
- 返回：mindspore的tensor。

In [2]:
import numpy as np
import mindspore as ms
import torch
import jax.numpy as jnp

input = np.array([ 0.3810,  1.2774, -0.2972, -0.3719,  0.4637])
other = np.array(0.5)

y1 = ms.ops.divide(ms.tensor(input), ms.tensor(other))
y2 = torch.divide(torch.tensor(input), torch.tensor(other))
y3 = jnp.divide(input, other)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax       output ->\n',y3)

mindspore output ->
 [ 0.762   2.5548 -0.5944 -0.7438  0.9274]
torch     output ->
 tensor([ 0.7620,  2.5548, -0.5944, -0.7438,  0.9274], dtype=torch.float64)
jax       output ->
 [ 0.762   2.5548 -0.5944 -0.7438  0.9274]


ms和jax不会输出类型。

In [7]:
input = np.array([[-0.3711, -1.9353, -0.4605, -0.2917],
                  [ 0.1815, -1.0111,  0.9805, -1.5923],
                  [ 0.1062,  1.4581,  0.7759, -1.2344],
                  [-0.1830, -0.0313,  1.1908, -1.4757]])
other = np.array([ 0.8032,  0.2930, -0.8113, -0.2308])

y1 = ms.ops.divide(ms.tensor(input), ms.tensor(other), rounding_mode='trunc')
y2 = torch.divide(torch.tensor(input), torch.tensor(other), rounding_mode='trunc')
y3 = jnp.divide(input, other)
print ('mindspore output ->\n',y1)
print ('torch     output ->\n',y2)
print ('jax     output ->\n',y3)

mindspore output ->
 [[-0. -6.  0.  1.]
 [ 0. -3. -1.  6.]
 [ 0.  4. -0.  5.]
 [-0. -0. -1.  6.]]
torch     output ->
 tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]], dtype=torch.float64)
jax     output ->
 [[-0.4620269  -6.605119    0.5676076   1.2638649 ]
 [ 0.22597112 -3.4508533  -1.2085541   6.899047  ]
 [ 0.13222112  4.97645    -0.95636636  5.348354  ]
 [-0.22783864 -0.10682594 -1.4677677   6.3938475 ]]


jax不支持向上向下取整。

In [8]:
out2 = torch.tensor([])

torch.divide(torch.tensor(input), torch.tensor(other), rounding_mode='trunc', out = out2)
print ('torch     output ->\n',out2)

torch     output ->
 tensor([[-0., -6.,  0.,  1.],
        [ 0., -3., -1.,  6.],
        [ 0.,  4., -0.,  5.],
        [-0., -0., -1.,  6.]])


torch还提供了出参的方式，ms未支持。

In [9]:
y1 = ms.ops.divide(input,other)

TypeError: Failed calling Div with "Div()(x=<class 'numpy.ndarray'>, y=<class 'numpy.ndarray'>)".
The valid calling should be: 
"Div()(x=<Number, Tensor>, y=<Number, Tensor>)".

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/ccsrc/pipeline/pynative/pynative_utils.cc:1294 PrintTypeCastError


In [10]:
y2 = torch.divide(input, other)

TypeError: divide() received an invalid combination of arguments - got (numpy.ndarray, numpy.ndarray), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Tensor other, *, str rounding_mode, Tensor out)
 * (Tensor input, Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!, !numpy.ndarray!)
 * (Tensor input, Number other, *, str rounding_mode)


In [3]:
y3 = jnp.divide(torch.tensor(input),other)

TypeError: Cannot interpret 'torch.float64' as a data type

当输入类型不正确时，报错信息torch最简洁明确。建议ms优化。